# Generated by Django 6.0 on 2026-01-02 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('code', 'Code Snippet')], default='text', max_length=20)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('text_content', models.TextField(blank=True, help_text='Markdown supported')),
                ('code_snippet', models.TextField(blank=True, help_text='Code to display')),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('is_free_preview', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.chapter')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
